export default async function Home() {
  return (
    <div className="flex flex-col p-6 gap-4">
      {/* 
        오버플로우 착각하지 않기 위해 넣어둔 요소입니다. 
        삭제 후 작업하기
      */}
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
      <div>hellow</div>
    </div>
  );
}
